controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: false
    rear_wheels_names: [left_rear_wheel_joint, right_rear_wheel_joint]
    front_wheels_names: [left_steering_hinge_joint, right_steering_hinge_joint]
    # Following three params have no effect.
    # odom_frame_id: odom
    # base_frame_id: base_link
    # enable_odom_tf: true

    wheelbase: 0.325
    front_wheel_track: 0.2
    rear_wheel_track: 0.2
    front_wheels_radius: 0.05
    rear_wheels_radius: 0.05

# joint_state_broadcaster:
#   ros__parameters:
