controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: false
    rear_wheels_names: [rear_left_wheel_joint, rear_right_wheel_joint]
    front_wheels_names: [front_left_steer_joint, front_right_steer_joint]
    # Following three params have no effect.
    # odom_frame_id: odom
    # base_frame_id: base_link
    # enable_odom_tf: true

    wheelbase: 2.86
    front_wheel_track: 1.534
    rear_wheel_track: 1.586
    front_wheels_radius: 0.31265
    rear_wheels_radius: 0.31265

# joint_state_broadcaster:
#   ros__parameters:
