controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    rear_joints_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    front_joints_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rear_joints_velocity_controller:
  ros__parameters:
    joints:
      - bl_axle
      - br_axle

front_joints_velocity_controller:
  ros__parameters:
    joints:
      - fl_axle
      - fr_axle

# joint_state_broadcaster:
#   ros__parameters:
