controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    axle_joints_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    front_steers_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

axle_joints_velocity_controller:
  ros__parameters:
    joints:
      - fl_axle
      - fr_axle
      - bl_axle
      - br_axle

front_steers_position_controller:
  ros__parameters:
    joints:
      - l_steer
      - r_steer

# joint_state_broadcaster:
#   ros__parameters:
